/oakd:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: false
      i_floodlight_brightness: 0
      i_laser_dot_brightness: 900
      i_nn_type: none
      i_pipeline_type: DEPTH
      i_usb_speed: SUPER_PLUS
    rgb:
      i_board_socket_id: 0
      i_fps: 30.0
      i_height: 720
      i_interleaved: false
      i_max_q_size: 10
      i_preview_size: 250
      i_enable_preview: false
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
      i_keep_preview_aspect_ratio: true
      i_publish_topic: false
      i_resolution: '1080P'
      i_width: 1280
    left:
      i_fps: 15.0
      i_resolution: '400P'
    right:
      i_resolution: '400P'
      i_fps: 15.0

    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_publish_right_rect: true
    use_sim_time: false

